### ISSUE TITLE
cuda not available with different torch version

### ISSUE THREAD

**Issue by heye0507** [turingaicloud/quickstart#3]
**Issue:** 
When creating new environment with pytorch version > 1.9.1, torchvision > 0.10.1 will result torch.cuda.is_avaiable() return false.

**Reproduce:**

environment:
    name: XXXXXXXX
    channels:
      - conda-forge
      - defaults
      - pytorch
    dependencies:
      - pytorch==1.10.1
      - torchvision==0.11.2
      - cudatoolkit=11.0 # or 11.3 / 11.2 / not explicit set cudatoolkit

Once the above environment is set, simply run a python script as following:

```
import torch
print(torch.__version__)
print(torch.cuda.is_avaiable()) # return False
print(torch.cuda.version) # print None
```

any pytorch version higher than 1.9.1 will result the above issue, or without explicit set cudatoolkit to 11.0. The default cudatoolkit for conda environment after pytorch 1.8.0 is 11.3.

**Expected behavior:** 

```
import torch
print(torch.__version__)
print(torch.cuda.is_avaiable()) # Should return True
print(torch.cuda.version) # Should return cuda version, for example, 11.0
```

cuda should be available with any pytorch version, or trigger error code prompt to user that TACC does not support pytorch version higher than 1.9.1 

**Possible cause of the issue**

Please check the reference issue from pytorch (https://github.com/pytorch/pytorch/issues/51858)

It seems to me that there is driver mismatch in TACC cuda servers, where nvcc is 11.0, nvidia-smi is 11.3 and pytorch cudatookit must match 11.0, therefore 1.9.1 is the last pytorch build that runs on 11.0.

**Current working build**

environment:
    name: XXXXXXXX
    channels:
      - conda-forge
      - defaults
      - pytorch
    dependencies:
      - pytorch==1.9.1
      - torchvision==0.10.1
      - cudatoolkit=11.0

**Comment by afzalxo** [comment]
Hi @heye0507 Did you ever find a solution to this issue. I am facing the same problem.

**Comment by heye0507** [comment]
> Hi @heye0507 Did you ever find a solution to this issue. I am facing the same problem.

I have posted a solution in the end of the issue. 
Here is a quick snap you can take a look, however, if you want to go beyond 1.9.1 will need a gpu driver upgrade on tacc side.

`environment:
name: XXXXXXXX
channels:
- conda-forge
- defaults
- pytorch
dependencies:
- pytorch==1.9.1
- torchvision==0.10.1
- cudatoolkit=11.0`

**Comment by heye0507** [comment]
- export CUDA_HOME=/mnt/data/cuda/cuda11.3.1
 - export PATH=$PATH:/mnt/data/cuda/cuda11.3.1/bin/

After discussing with TACC team, now user can manually setup cuda driver path. After explicit indicating cuda driver path, I confirm that the cuda not available issue is resolved. Now you can upgrade to any pytorch version with proper cudatoolkit and torchvision.

Thank you so much for the team support!
